version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-virus-tracker:latest
    env_file:
      - .env
    environment:
      - PORT=5007
      - MONGODB_URI=mongodb://ct-virus-tracker-db:27017/ct-virus-tracker-db
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - ct-virus-tracker-db

  ct-virus-tracker-db:
    image: mongo:3.6.4
