version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-visit-manager:latest
    environment:
      - PORT=5007
    ports:
      - "5007:5007"
    depends_on:
      - contact-tracing-db

  contact-tracing-db:
    image: mongo:3.6.4
