version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-virus-tracker:latest
    environment:
      - PORT=5007
      - MONGODB_URI=mongodb://ct-virus-tracker-db:27017/ct-virus-tracker-db
      - QUEUE_ADDRESS=amqp://guest:guest@codes-queue:5672/
      - QUEUE_NAME=infected-codes
    ports:
      - "5007:5007"
    depends_on:
      - ct-virus-tracker-db

  ct-virus-tracker-db:
    image: mongo:3.6.4

  codes-queue:
    image: rabbitmq:3-management-alpine
    container_name: 'codes-queue'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - queue-network

networks:
  queue-network: